# Generated by Django 5.0.6 on 2026-06-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('bot_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('error', 'خطا در توکن')], default='active', max_length=20)),
                ('webhook_set', models.BooleanField(default=False)),
                ('welcome_text', models.TextField(blank=True, default='سلام! خوش اومدی 👋')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='bots.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(editable=False, max_length=32, unique=True)),
                ('file_id', models.CharField(max_length=255)),
                ('file_unique_id', models.CharField(blank=True, max_length=100)),
                ('file_type', models.CharField(choices=[('photo', 'عکس'), ('video', 'ویدیو'), ('document', 'فایل'), ('audio', 'صدا'), ('voice', 'ویس'), ('animation', 'گیف')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bots.childbot')),
            ],
        ),
    ]
